name = "ACEapi"
uuid = "69e0c927-b120-467d-b2b3-5b6842148cf4"
authors = ["Teemu Järvinen <teemu.j.jarvinen@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
